name: dev-timer
run-name: ${{ github.actor }} Update Radme
on:
  push:
    paths:
      - 'dev-timer/*'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.6
      - run: cd dev-timer && go run main.go

