name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    paths:
      - 'dev-timer/**.json'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.6
      - run: cd dev-timer && go run main.go
